[build]
  publish = "."
  functions = "netlify/functions"
  node_bundler = "esbuild"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []
  included_files = []

[build.environment]
  NODE_VERSION = "18"
